### ISSUE TITLE
need some help getting the code running

### ISSUE THREAD

**Issue by Nhubbers** [Open-Power-System-Data/weather_data#2]
Seems a SSL connection can not be made in step "4.1 Get wind data". 

WARNING:opendap_download:<urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)>

Does someone has a suggestion how to fix this?

**Comment by JanUrb** [comment]
It seems like the structure of the MERRA-2 opendap interface is currently being changed. Therefore the script is not working. I will have to wait for the final changes to fix the errors.

**Comment by arjunane** [comment]
The issue with the bad SSL certificate is solved here:
http://stackoverflow.com/a/41716365/7105351 

In addition i changed these urls:
BASE_URL = 'https://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/'
ROUGHNESS_BASE_URL = 'https://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXFLX.5.12.4/'
dimension_url = 'https://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/2014/01/MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4.nc4?'

Now i get warnings, that i connect to a unsecure ssl server, but at least the script is running again.

**Comment by JanUrb** [comment]
It seems like changing the URLs is enough. Accessing a URL (for example https://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/2014/01/MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4.ascii?U2M[0:1:2][0:1:2][0:1:5],time[0:1:2]) with the brower does not give me any ssl errors.

**Comment by GiorgioBalestrieri** [comment]
Hi, I just faced a similar error and had to update the url (for wind data, in my case) to
```
BASE_URL = 'https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/'
```

This [https://developer.earthdata.nasa.gov/opendap/resources/eosdis-opendap-servers](https://developer.earthdata.nasa.gov/opendap/resources/eosdis-opendap-servers) seems a good source with the up-to-date URL for different services.
