### ISSUE TITLE
Actual solar generation time series for Spain 2015 has non-zero loads for every hour of the year

### ISSUE THREAD

**Issue by redekok** [Open-Power-System-Data/weather_data#6]
For the actual solar generation time series for Spain 2015 (ES_solar_generation_actual, hourly based time series, from 2015-01-01 to 2015-12-31) there are non-zero loads for every hour of the year. I would expect the loads to be zero between sunset and sunrise.

![image](https://user-images.githubusercontent.com/5946498/81563609-c6ecb300-9396-11ea-8029-5e098c3e5538.png)

I would be very interested in finding out why this is the case.

**Comment by JuanIgnacioGil** [comment]
Can it be some residual thermo solar generation?

**Comment by jgmill** [comment]
@JuanIgnacioGil is right. That is [concentrated solar power ](https://en.wikipedia.org/wiki/Solar_power_in_Spain#Solar_thermal_power_plants)(CSP).
